import Head from 'next/head'
import About from '../components/About'
import Buy from '../components/Buy'
import Footer from '../components/Footer'
import Hero from '../components/HeroContainer'
import Members from '../components/Members'
import Modules from '../components/Modules'
import Opinions from '../components/Opinions'
import Questions from '../components/Questions'
import { Container } from '../styles/Home'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Anatomia Palpatória Avançada</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Hero />
        <About />
        <Members />
        <Modules />
        <Opinions />
        <Buy />
        <Questions />
      </main>

      <Footer />
    </Container>
  )
}
