import Head from "next/head";
import Footer from "../components/Footer";
import HeroTerms from "../components/HeroTerms";
import ScrollToTop from "../components/ScrollToTop";
import Terms from "../components/Terms";
import { Container } from "../styles/Terms";

export default function TermsPage() {
  return (
    <Container>
      <Head>
        <title>Anatomia Palpatória Avançada - Termos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="terms_container">
        <HeroTerms />
        <Terms />
      </main>
      <ScrollToTop />
      <Footer />
    </Container>
  )
}
